apiVersion: v1
kind: Service
metadata:
  name: cust-auth-plugin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cust-auth-plugin
spec:
  selector:
    app.kubernetes.io/name: cust-auth-plugin
  ports:
    - protocol: TCP
      port: 55778
      targetPort: 55778
